# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ica_map_v2
                                 A QGIS plugin
 test version of ICA map on 0726
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-26
        copyright            : (C) 2024 by World Food Program
        email                : Xiaomeng Wu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ica_map_v2 class from file ica_map_v2.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ica_map_v2 import ica_map_v2
    return ica_map_v2(iface)
